name: UnlimitedGrind
version: 0.1
main: be.sixefyle.UnlimitedGrind
description: An example plugin
author: Sixefyle
api-version: 1.19
depend: [Vault, IridiumSkyblock, ProtocolLib]
softdepend: [RealScoreboard]
commands:
  ugreload:
    description: Reload UG Core plugin
    aliases:
      - ureload
      - urel
    permission: ug.admin
    permission-message: You do not have permission!
    usage: /ugreload
  power:
    description: Power commands
    aliases:
      - pow
    permission: ug.admin
    permission-message: You do not have permission!
    usage: /power help
  randomgive:
    description: Power commands
    aliases:
      - rg
    permission: ug.admin
    permission-message: You do not have permission!
    usage: /randomgive <power>
  arena:
    description: Arena commands
    aliases:
      - a
    permission: ug.player
    permission-message: You do not have permission!
    usage: /arena <power>
  group:
    description: Group commands
    aliases:
      - g
    permission: ug.player
    permission-message: You do not have permission!
    usage: /group help